- title: מחקר מוצרים
  icon: fas fa-flask sr-icon-1
  description:
    - מחקר נישות ומוצרים מקבילים חינם למוצר שלך באמזון.
    - ניתוח מעמיק של מתחרים, אופן שיווק ועלויות כדי להעריך את סיכויי ההצלחה של המוצר שלך באמזון.

- title: הקמת חנות ועמוד מוצר
  icon: fas fa-clipboard-list sr-icon-1
  description:
    - יצירת ליסט שידגיש את היתרונות החשובים ביותר של המוצר שלך, ויעזור לך לקדם אותו באמזון.
    - ליסט מלא כולל תיאור מוצר ופיצ'רים חשובים בעזרת כותב תוכן ייעודי.
    - תמונות ועיצובים מקצועיים (lifestyle, infographics ו-composite).

- title: ייצור
  icon: fas fa-industry sr-icon-1
  description:
    - מציאת ספקים איכותיים בסין, וויאטנם וארה"ב למוצרים או אביזרים נלווים שתרצה להוסיף למוצר שלך.
    - ייעוץ בשיטות בידול של המוצר שלך באמזון כדי לבנות הצעה שלקוחות לא יוכלו לסרב לה.

- title: השקה ושיווק
  icon: fas fa-users sr-icon-1
  description:
    - שיווק בתוך אמזון דרך יצירת וניהול קמפייני PPC חכמים.
    - יצירת תוכן בעל ערך מוסף שמותאם ללקוחות אמזון.
    - הקמת קמפייני שיווק בפלטפורמות חיצוניות כדי לאתר ולשמר לקוחות פוטנציאליים למוצר שלך.

- title: אופטימיזציות
  icon: fas fa-cogs sr-icon-1
  description:
    - הרצת קמפייני Split-testing A/B כדי לשפר את הליסט שלך ולהשיג אחוז המרה גבוה יותר של מבקרים בליסט.
    - ליסט מלא כולל תיאור מוצר ופיצ'רים חשובים בעזרת כותב תוכן ייעודי
    - עבודת תחזוק שוטפת של ניהול ומענה ללקוחות וסוקרים בליסט שלך.
    - טיפול בבעיות מול אמזון.
